# coding:utf-8
# author:tntC4stl3

'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''

from math import sqrt
def numOfFactors(num):
	'''从1到sqrt(num)，如果有n个数能被num整除，说明整个有2n个数能被num整除'''
	count = 0
	tmp = int(sqrt(num))
	for i in range(1, tmp):
		if num % i == 0:
			count += 1
	if pow(tmp, 2) == num:
		return count * 2 - 1
	else:
		return count * 2

if __name__ == '__main__':
	num = 1
	count = 1
	while numOfFactors(num) < 500:
		count += 1
		num += count
	print num