# coding:utf-8
# author:tntC4stl3

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

fib = [1, 2]
i = 1
# 得到完整的fib列表
while True:
	tmp = fib[i] + fib[i-1]
	if tmp > 4000000:
		break
	fib.append(tmp)
	i += 1

result = 0
for i in range(1, len(fib), 3): # 偶数的规律是从第二个数开始，每隔3个数就为偶数
	result += fib[i]

print result